
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-08
owner: ucsb-cs156-f24
repo_name: team02-f24-08
pull_requests: [{"author":{"id":"MDQ6VXNlcjUzMjc5MDkx","is_bot":false,"login":"qwistaycat","name":"Christy Yu"},"headRefName":"cy-Articles-copy-placeholders","number":89,"title":"added Articles placeholder pages and tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/89"},{"author":{"id":"MDQ6VXNlcjUzMjc5MDkx","is_bot":false,"login":"qwistaycat","name":"Christy Yu"},"headRefName":"cy-Articles-fixtures","number":88,"title":"added Articles fixtures","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/88"},{"author":{"id":"U_kgDOBcsiCw","is_bot":false,"login":"obenedek20","name":""},"headRefName":"Oscar-EditPage","number":85,"title":"Oscar - Edit page plus tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/85"},{"author":{"id":"U_kgDOBcsiCw","is_bot":false,"login":"obenedek20","name":""},"headRefName":"Oscar-IndexPage","number":83,"title":"Oscar - Index Page for MenuItemReview is created, tested","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/83"},{"author":{"id":"MDQ6VXNlcjUzMjc5MDkx","is_bot":false,"login":"qwistaycat","name":"Christy Yu"},"headRefName":"cy-Articles-backend","number":67,"title":"added Articles backend files","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/67"}]
