
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-08
owner: ucsb-cs156-f24
repo_name: team02-f24-08
pull_requests: [{"author":{"id":"U_kgDOCu01tQ","is_bot":false,"login":"divyanipunj","name":""},"headRefName":"dp-HelpRequest-editPage","number":115,"title":"Dp - helprequest edit page","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/115"},{"author":{"id":"U_kgDOCu01tQ","is_bot":false,"login":"divyanipunj","name":""},"headRefName":"dp-HelpRequest-createPage","number":114,"title":"dp - helprequest: create page","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/114"},{"author":{"id":"U_kgDOCMNTCg","is_bot":false,"login":"Mike-Petrus","name":""},"headRefName":"Mike-RecommendationRequest-editPage","number":113,"title":"Mike-Recommendation request edit page + tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/113"},{"author":{"id":"MDQ6VXNlcjUzMjc5MDkx","is_bot":false,"login":"qwistaycat","name":"Christy Yu"},"headRefName":"cy-Create-Page-for-Articles","number":112,"title":"Christy - added Articles create page","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/112"},{"author":{"id":"MDQ6VXNlcjUzMjc5MDkx","is_bot":false,"login":"qwistaycat","name":"Christy Yu"},"headRefName":"cy-Edit-Page-for-Articles","number":111,"title":"Christy - added Articles edit page","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/111"},{"author":{"id":"U_kgDOCMNTCg","is_bot":false,"login":"Mike-Petrus","name":""},"headRefName":"Mike-RecommendationRequest-indexPage","number":109,"title":"Mike-Recommendation request index page","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/109"},{"author":{"id":"MDQ6VXNlcjUzMjc5MDkx","is_bot":false,"login":"qwistaycat","name":"Christy Yu"},"headRefName":"cy-Index-Page-for-Articles","number":103,"title":"Christy - added Articles index page","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/103"}]
