
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-08
owner: ucsb-cs156-f24
repo_name: team02-f24-08
pull_requests: [{"author":{"id":"U_kgDOCMNTCg","is_bot":false,"login":"Mike-Petrus","name":""},"headRefName":"Mike-RecommendationRequest-formComponent","number":82,"title":"Mike-Recommendation request form component","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/82"},{"author":{"id":"MDQ6VXNlcjY4MDg2NzYw","is_bot":false,"login":"yw2398","name":"Amber Wang"},"headRefName":"AW-UCSBOrgs-FormComponent","number":81,"title":"(TEST,not ready for review yet) AW-Form Componenet for UCSB Orgs","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/81"},{"author":{"id":"MDQ6VXNlcjUzMjc5MDkx","is_bot":false,"login":"qwistaycat","name":"Christy Yu"},"headRefName":"cy-Articles-backend","number":67,"title":"added Articles backend files","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/67"}]
