
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-08
owner: ucsb-cs156-f24
repo_name: team02-f24-08
pull_requests: [{"author":{"id":"U_kgDOCMNTCg","is_bot":false,"login":"Mike-Petrus","name":""},"headRefName":"Mike-RecommendationRequest-indexPage","number":109,"title":"Mike-Recommendation request index page","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/109"},{"author":{"id":"MDQ6VXNlcjY4MDg2NzYw","is_bot":false,"login":"yw2398","name":"Amber Wang"},"headRefName":"AW-Create-UCSBOrg","number":107,"title":"AW-create page for UCSB Orgs","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/107"},{"author":{"id":"U_kgDOCMNTCg","is_bot":false,"login":"Mike-Petrus","name":""},"headRefName":"Mike-RecommendationRequest-createPage","number":106,"title":"Mike-Recommendation request create page + tests/stories","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/106"},{"author":{"id":"MDQ6VXNlcjY4MDg2NzYw","is_bot":false,"login":"yw2398","name":"Amber Wang"},"headRefName":"AW-CopyPlaceholder","number":104,"title":"AW-Copy Placeholders for UCSBOrganization pages; add to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/104"},{"author":{"id":"MDQ6VXNlcjUzMjc5MDkx","is_bot":false,"login":"qwistaycat","name":"Christy Yu"},"headRefName":"cy-Index-Page-for-Articles","number":103,"title":"Christy - added Articles create page","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/103"}]
