
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-08
owner: ucsb-cs156-f24
repo_name: team02-f24-08
pull_requests: [{"author":{"id":"U_kgDOCu01tQ","is_bot":false,"login":"divyanipunj","name":""},"headRefName":"dp-HelpRequest-backend","number":68,"title":"copied all the files for backend CRUD API (helprequest)","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/68"},{"author":{"id":"MDQ6VXNlcjUzMjc5MDkx","is_bot":false,"login":"qwistaycat","name":"Christy Yu"},"headRefName":"cy-Articles-backend","number":67,"title":"added Articles backend files","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/67"},{"author":{"id":"U_kgDOBtIn9Q","is_bot":false,"login":"caleb-stahl","name":""},"headRefName":"caleb-DCMIFixtures","number":66,"title":"Caleb-dcmi fixtures","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/66"},{"author":{"id":"U_kgDOBtIn9Q","is_bot":false,"login":"caleb-stahl","name":""},"headRefName":"caleb-portOldCode","number":63,"title":"adding files from team01","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/63"}]
