
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-08
owner: ucsb-cs156-f24
repo_name: team02-f24-08
pull_requests: [{"author":{"id":"U_kgDOBtIn9Q","is_bot":false,"login":"caleb-stahl","name":""},"headRefName":"caleb-TC","number":80,"title":"Caleb- Table Component and Tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/80"},{"author":{"id":"MDQ6VXNlcjY4MDg2NzYw","is_bot":false,"login":"yw2398","name":"Amber Wang"},"headRefName":"AW-create-fixtures","number":79,"title":"AW-create fixtures for UCSB Orgs","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/79"},{"author":{"id":"U_kgDOBcsiCw","is_bot":false,"login":"obenedek20","name":""},"headRefName":"Oscar-CreatePage","number":77,"title":"Oscar - Create Page fully functional for MenuItemReview","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/77"},{"author":{"id":"U_kgDOBcsiCw","is_bot":false,"login":"obenedek20","name":""},"headRefName":"Oscar-EditCreatePages","number":75,"title":"Oscar - Added Placeholder Create and Edit Pages","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/75"},{"author":{"id":"U_kgDOBcsiCw","is_bot":false,"login":"obenedek20","name":""},"headRefName":"Oscar-MenuItemTable","number":73,"title":"Oscar - MenuItemReview now has table component, tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/73"},{"author":{"id":"MDQ6VXNlcjUzMjc5MDkx","is_bot":false,"login":"qwistaycat","name":"Christy Yu"},"headRefName":"cy-Articles-backend","number":67,"title":"added Articles backend files","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/67"}]
