
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team02-f24-08
owner: ucsb-cs156-f24
repo_name: team02-f24-08
pull_requests: [{"author":{"id":"U_kgDOCu01tQ","is_bot":false,"login":"divyanipunj","name":""},"headRefName":"dp-HelpRequest-form","number":97,"title":"Form component for HelpRequest and tests.","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/97"},{"author":{"id":"MDQ6VXNlcjY4MDg2NzYw","is_bot":false,"login":"yw2398","name":"Amber Wang"},"headRefName":"AW-UCSBOrg-Form","number":94,"title":"AW-Added Form Component for UCSB Org","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/94"},{"author":{"id":"U_kgDOCMNTCg","is_bot":false,"login":"Mike-Petrus","name":""},"headRefName":"Mike-RecommendationRequest-tableComponent","number":92,"title":"Mike-Recommendation request table component + tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/92"},{"author":{"id":"MDQ6VXNlcjUzMjc5MDkx","is_bot":false,"login":"qwistaycat","name":"Christy Yu"},"headRefName":"cy-Articles-table-component","number":91,"title":"Christy - added Articles table component","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/91"},{"author":{"id":"MDQ6VXNlcjUzMjc5MDkx","is_bot":false,"login":"qwistaycat","name":"Christy Yu"},"headRefName":"cy-Articles-form-component","number":90,"title":"Christy - added Articles form component","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/90"},{"author":{"id":"MDQ6VXNlcjUzMjc5MDkx","is_bot":false,"login":"qwistaycat","name":"Christy Yu"},"headRefName":"cy-Articles-copy-placeholders","number":89,"title":"Christy - added Articles placeholder pages and tests","url":"https://github.com/ucsb-cs156-f24/team02-f24-08/pull/89"}]
